[workspace]
members = [
    "crates/t-cli",
    "crates/t-lib",
    "crates/t-vnc",
    # ""
]
resolver = "2"

[workspace.dependencies]
t-cli = { path = "./crates/t-cli" }
t-lib = { path = "./crates/t-lib" }
t-vnc = { path = "./crates/t-vnc" }

# normal
clap = { version = "4.4.11", features = ["derive"] }
dotenv = { version = "0.15.0" }
home = { version = "0.5.9" }
log = { version = "0.4.20" }
env_logger = { version = "0.10.1" }
anyhow = { version = "1.0.76" }
shell-escape = { version = "0.1.5" }

# script engine
quick-js = { version = "0.4.1" }
mlua = { version = "0.9.1", features = ["lua54", "vendored"] }
pyo3 = { version = "0.20.0", features = ["auto-initialize"] }

# console
ssh2 = { version = "0.9.4", features = ["vendored-openssl"] }
