[package]
name    = "t-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "autotest"
path = "bin/autotest.rs"

[dependencies]
t-console = { workspace = true }
t-vnc     = { workspace = true }
t-binding = { workspace = true }
t-util    = { workspace = true }
t-config  = { workspace = true }

tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
clap               = { workspace = true }
dotenv             = { workspace = true }
home               = { workspace = true }
anyhow             = { workspace = true }
shell-escape       = { workspace = true }
serde              = { workspace = true }
toml               = { workspace = true }
quick-js           = { workspace = true }
mlua               = { workspace = true }
pyo3               = { workspace = true }
ssh2               = { workspace = true }
