[package]
name    = "t-binding"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
t-console = { workspace = true }

tracing            = { workspace = true }
tracing-subscriber = { workspace = true }
quick-js           = { workspace = true }
rquickjs           = { workspace = true }
mlua               = { workspace = true }
pyo3               = { workspace = true }
