[console]

[console.ssh]
enable   = true
host     = "127.0.0.1"
port     = 22
password = ""

[console.serial]
enable      = true
serial_file = "/dev/ttyUSB0"

[console.vnc]
enable   = false
ip       = "127.0.0.1"
port     = 5900
password = ""
